# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 614b5937cbf1c1b8a80f21b00f9e3a2ff03e1f1b84a607b55238f029f2eed676e951ffc9c78c535a0bd23c6d3c142a055a955fcd8d70720bd7c68504605c2195

test:
  secret_key_base: 4914eacbefbf0cbff772949f80399d2b0a498f5d4bedc69ab26bf6ec2a169744c7126f0cfa0eb2f31f355a6abde9b1df023233f730b3b085493dbfaeba633f74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
